/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.CustomerDashboardController;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ALVA
 */
public class CustomerDashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CustomerDashboard.class.getName());
    private CustomerDashboardController controller;
    
    /**
     * Creates new form CustomerDashboard
     */
    public CustomerDashboard(CustomerDashboardController controller) {
        setController(controller);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField4 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelCustomer = new javax.swing.JTable();
        ButtonBeli = new javax.swing.JButton();
        Cari = new javax.swing.JTextField();
        ButtonCari = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Nama = new javax.swing.JTextField();
        Kategori = new javax.swing.JTextField();
        Satuan = new javax.swing.JTextField();
        HargaSatuan = new javax.swing.JTextField();
        Stok = new javax.swing.JTextField();
        JumlahBeli = new javax.swing.JTextField();
        HargaTotal = new javax.swing.JTextField();
        clear = new javax.swing.JButton();

        jTextField4.setText("jTextField2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TabelCustomer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nama Barang", "Kategori", "Satuan", "Harga Satuan", "Stok"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TabelCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelCustomerMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabelCustomer);
        if (TabelCustomer.getColumnModel().getColumnCount() > 0) {
            TabelCustomer.getColumnModel().getColumn(0).setMinWidth(0);
            TabelCustomer.getColumnModel().getColumn(0).setPreferredWidth(0);
            TabelCustomer.getColumnModel().getColumn(0).setMaxWidth(0);
            TabelCustomer.getColumnModel().getColumn(1).setResizable(false);
            TabelCustomer.getColumnModel().getColumn(3).setResizable(false);
            TabelCustomer.getColumnModel().getColumn(4).setResizable(false);
        }

        ButtonBeli.setText("Beli");
        ButtonBeli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonBeliMouseClicked(evt);
            }
        });

        Cari.setText("Cari barang");

        ButtonCari.setText("Cari");
        ButtonCari.addActionListener(this::ButtonCariActionPerformed);

        jLabel1.setText("Nama");

        jLabel2.setText("Kategori");

        jLabel3.setText("Satuan");

        jLabel4.setText("Harga Satuan");

        jLabel5.setText("Stok");

        jLabel6.setText("Jumlah Beli");

        jLabel7.setText("Harga Total");

        Nama.setEditable(false);

        Kategori.setEditable(false);

        Satuan.setEditable(false);

        HargaSatuan.setEditable(false);

        Stok.setEditable(false);

        JumlahBeli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                JumlahBeliKeyReleased(evt);
            }
        });

        HargaTotal.setEditable(false);

        clear.setText("Clear");
        clear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearMouseClicked(evt);
            }
        });
        clear.addActionListener(this::clearActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(HargaTotal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                                    .addComponent(JumlahBeli, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Stok, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(HargaSatuan, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Satuan, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Kategori, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Nama, javax.swing.GroupLayout.Alignment.LEADING)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(Cari, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ButtonCari)))
                        .addGap(0, 38, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(clear)
                        .addGap(41, 41, 41)
                        .addComponent(ButtonBeli)
                        .addGap(73, 73, 73))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonCari))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Kategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Satuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(HargaSatuan, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Stok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JumlahBeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(28, 28, 28))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(HargaTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonBeli)
                    .addComponent(clear))
                .addContainerGap(48, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TabelCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelCustomerMouseClicked
        // TODO add your handling code here:
        controller.tabelMouseClickedHandle();
    }//GEN-LAST:event_TabelCustomerMouseClicked

    private void ButtonBeliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonBeliMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonBeliMouseClicked

    private void clearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearMouseClicked
        controller.clearMouseClickedHandle();
    }//GEN-LAST:event_clearMouseClicked

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        controller.clearMouseClickedHandle();
    }//GEN-LAST:event_clearActionPerformed

    private void ButtonCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCariActionPerformed
        // TODO add your handling code here:
        controller.tombolCariMouseClickedHandle();
    }//GEN-LAST:event_ButtonCariActionPerformed

    private void JumlahBeliKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JumlahBeliKeyReleased
        // TODO add your handling code here:
        controller.jumlahBeliHandle();
    }//GEN-LAST:event_JumlahBeliKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> new CustomerDashboard().setVisible(true));
    }

    void setController(CustomerDashboardController controller) {
        this.controller = controller;
    }
    
    public DefaultTableModel getTableModel() {
        return (DefaultTableModel) this.TabelCustomer.getModel();
    }
    
    public JTable getTable() {
        return this.TabelCustomer;
    }
    
    public void setNama(String s) {
        this.Nama.setText(s);
    }

    public String getNama() {
        return this.Nama.getText();
    }
    
    public void setKategori(String s) {
        this.Kategori.setText(s);
    }

    public String getKategori() {
        return this.Kategori.getText();
    }
    
    public void setSatuan(String s) {
        this.Satuan.setText(s);
    }

    public String getSatuan() {
        return this.Satuan.getText();
    }
    
    public void setHarga(String s) {
        this.HargaSatuan.setText(s);
    }

    public String getHarga() {
        return this.HargaSatuan.getText();
    }
    
    public void setStok(String s) {
        this.Stok.setText(s);
    }

    public String getStok() {
        return this.Stok.getText();
    }
    
    public void setTextCari(String s) {
        this.Cari.setText(s);
    }

    public String getTextCari() {
        return this.Cari.getText();
    }
    
    public void setJumlahBeli(String s) {
        this.JumlahBeli.setText(s);
    }

    public String getJumlahBeli() {
        return this.JumlahBeli.getText();
    }

    public void setHargaTotal(String s) {
        this.HargaTotal.setText(s);
    }

    public String getHargaTotal() {
        return this.HargaTotal.getText();
    }
    


    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonBeli;
    private javax.swing.JButton ButtonCari;
    private javax.swing.JTextField Cari;
    private javax.swing.JTextField HargaSatuan;
    private javax.swing.JTextField HargaTotal;
    private javax.swing.JTextField JumlahBeli;
    private javax.swing.JTextField Kategori;
    private javax.swing.JTextField Nama;
    private javax.swing.JTextField Satuan;
    private javax.swing.JTextField Stok;
    private javax.swing.JTable TabelCustomer;
    private javax.swing.JButton clear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
